// EPAU mock data. Illustrative, not official.
// Ported from docs/design/data.jsx. Using Guyanese series from the
// 'Guyana Key Statistics' workbook.

import type {
  Indicator,
  SavedView,
  ComparisonTable,
  IngestionRun,
  NrfRow,
  PscRow,
  GdpRow,
  NplRow,
} from './types';

export const INDICATORS: Indicator[] = [
  {
    id: 'psc_total',
    name: 'Private Sector Credit, Total',
    category: 'Monetary',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Statistical Bulletin Tbl 3.4',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Monetary_03',
  },
  {
    id: 'psc_business',
    name: 'Private Sector Credit, Business Enterprises',
    category: 'Monetary',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Statistical Bulletin Tbl 3.4',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Monetary_03',
  },
  {
    id: 'psc_mortgages',
    name: 'Private Sector Credit, Real Estate Mortgages',
    category: 'Monetary',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Statistical Bulletin Tbl 3.4',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Monetary_03',
  },
  {
    id: 'psc_households',
    name: 'Private Sector Credit, Households',
    category: 'Monetary',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Statistical Bulletin Tbl 3.4',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Monetary_03',
  },
  {
    id: 'nrf_inflows_actual',
    name: 'NRF Inflows, Actual',
    category: 'Fiscal',
    frequency: 'Annual',
    latest: '2025',
    source: 'Ministry of Finance, NRF Quarterly Reports',
    unit: 'US$ millions',
    caveat:
      'Royalties recorded on cash basis; 2025 figures provisional pending audit.',
    sheet: 'Fiscal_22',
  },
  {
    id: 'nrf_inflows_budget',
    name: 'NRF Inflows, Budget',
    category: 'Fiscal',
    frequency: 'Annual',
    latest: '2026',
    source: 'National Budget Speech, Appendix III',
    unit: 'US$ millions',
    caveat: null,
    sheet: 'Fiscal_22',
  },
  {
    id: 'gdp_real_growth',
    name: 'Real GDP Growth, Overall',
    category: 'Macro',
    frequency: 'Annual',
    latest: '2025',
    source: 'Bureau of Statistics, National Accounts',
    unit: 'percent',
    caveat:
      '2025 is a first estimate; subject to revision with Q4 national accounts release.',
    sheet: 'Macro_01',
  },
  {
    id: 'gdp_nonoil_growth',
    name: 'Real GDP Growth, Non-Oil',
    category: 'Macro',
    frequency: 'Annual',
    latest: '2025',
    source: 'Bureau of Statistics, National Accounts',
    unit: 'percent',
    caveat: null,
    sheet: 'Macro_01',
  },
  {
    id: 'npl_ratio',
    name: 'Non-Performing Loans Ratio',
    category: 'Monetary',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Bank of Guyana, Financial Stability Report',
    unit: 'percent',
    caveat: null,
    sheet: 'Monetary_11',
  },
  {
    id: 'cpi_yoy',
    name: 'CPI Inflation, 12-month',
    category: 'Macro',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bureau of Statistics, CPI Release',
    unit: 'percent',
    caveat: null,
    sheet: 'Macro_12',
  },
  {
    id: 'fx_rate_avg',
    name: 'Exchange Rate, Period Average',
    category: 'External',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Mid-Rate Series',
    unit: 'G$ per US$',
    caveat:
      'Series reflects mid-rate; cambio rates may differ by up to 1.5 percent.',
    sheet: 'External_04',
  },
  {
    id: 'fx_reserves',
    name: 'Gross International Reserves',
    category: 'External',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, International Reserves',
    unit: 'US$ millions',
    caveat: null,
    sheet: 'External_01',
  },
  {
    id: 'debt_ext',
    name: 'External Public Debt Stock',
    category: 'Debt',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Ministry of Finance, Debt Management Division',
    unit: 'US$ millions',
    caveat: null,
    sheet: 'Debt_02',
  },
  {
    id: 'debt_dom',
    name: 'Domestic Public Debt Stock',
    category: 'Debt',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Ministry of Finance, Debt Management Division',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Debt_03',
  },
  {
    id: 'fiscal_revenue',
    name: 'Central Government Revenue, Total',
    category: 'Fiscal',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Ministry of Finance, Fiscal Out-Turn',
    unit: 'G$ millions',
    caveat: null,
    sheet: 'Fiscal_01',
  },
  {
    id: 'fiscal_expenditure',
    name: 'Central Government Expenditure, Total',
    category: 'Fiscal',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Ministry of Finance, Fiscal Out-Turn',
    unit: 'G$ millions',
    caveat:
      'Capital expenditure reclassified in 2023; pre-2023 values not strictly comparable.',
    sheet: 'Fiscal_01',
  },
  {
    id: 'oil_production',
    name: 'Crude Oil Production',
    category: 'External',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Ministry of Natural Resources, Petroleum Production Report',
    unit: 'thousand barrels per day',
    caveat: null,
    sheet: 'External_21',
  },
  {
    id: 'unemployment',
    name: 'Unemployment Rate',
    category: 'Social',
    frequency: 'Annual',
    latest: '2024',
    source: 'Labour Force Survey, Bureau of Statistics',
    unit: 'percent',
    caveat:
      'LFS methodology revised in 2021; figures pre-2021 not directly comparable.',
    sheet: 'Social_04',
  },
  {
    id: 'because_rollout',
    name: 'BECAUSE Cash Transfer, Beneficiaries',
    category: 'Social',
    frequency: 'Annual',
    latest: '2025',
    source: 'Ministry of Human Services, Programme Reports',
    unit: 'persons',
    caveat: null,
    sheet: 'Social_17',
  },
  {
    id: 'bop_current',
    name: 'Current Account Balance',
    category: 'External',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Bank of Guyana, Balance of Payments',
    unit: 'US$ millions',
    caveat: null,
    sheet: 'External_11',
  },
  {
    id: 'bop_capital',
    name: 'Capital and Financial Account Balance',
    category: 'External',
    frequency: 'Quarterly',
    latest: 'Q4 2025',
    source: 'Bank of Guyana, Balance of Payments',
    unit: 'US$ millions',
    caveat: null,
    sheet: 'External_11',
  },
  {
    id: 'gini',
    name: 'Gini Coefficient',
    category: 'Social',
    frequency: 'Annual',
    latest: '2024',
    source: 'Bureau of Statistics, Household Budget Survey',
    unit: 'index',
    caveat: 'Derived from HBS 2019 and 2024; intercensal years imputed.',
    sheet: 'Social_31',
  },
  {
    id: 'tbill_91',
    name: '91-day Treasury Bill Rate',
    category: 'Monetary',
    frequency: 'Monthly',
    latest: 'Feb 2026',
    source: 'Bank of Guyana, Auction Results',
    unit: 'percent',
    caveat: null,
    sheet: 'Monetary_21',
  },
];

// NRF actual vs budget, annual, 2020-2026 (US$ millions, illustrative)
export const NRF_SERIES: NrfRow[] = [
  { year: '2020', actual: 70, budget: 80 },
  { year: '2021', actual: 410, budget: 420 },
  { year: '2022', actual: 1270, budget: 1250 },
  { year: '2023', actual: 1620, budget: 1800 },
  { year: '2024', actual: 2690, budget: 2550 },
  { year: '2025', actual: 2450, budget: 2900 },
  { year: '2026', actual: null, budget: 2800 },
];

// Private sector credit by sector since 2015, annual (G$ millions, illustrative)
export const PSC_SERIES: PscRow[] = [
  { year: '2015', business: 132000, mortgages: 52000, households: 24000 },
  { year: '2016', business: 138000, mortgages: 56000, households: 25000 },
  { year: '2017', business: 145000, mortgages: 60000, households: 26500 },
  { year: '2018', business: 152000, mortgages: 66000, households: 28000 },
  { year: '2019', business: 168000, mortgages: 74000, households: 30500 },
  { year: '2020', business: 178000, mortgages: 82000, households: 32000 },
  { year: '2021', business: 192000, mortgages: 92000, households: 34500 },
  { year: '2022', business: 215000, mortgages: 108000, households: 38000 },
  { year: '2023', business: 238000, mortgages: 128000, households: 42500 },
  { year: '2024', business: 258000, mortgages: 152000, households: 47000 },
  { year: '2025', business: 272000, mortgages: 168000, households: 49500 },
  { year: '2026', business: 278000, mortgages: 172000, households: 50800 },
];

// Real GDP growth, overall + non-oil, annual
export const GDP_SERIES: GdpRow[] = [
  { year: '2017', overall: 2.1, nonoil: 1.9 },
  { year: '2018', overall: 4.4, nonoil: 2.8 },
  { year: '2019', overall: 5.4, nonoil: 4.5 },
  { year: '2020', overall: 43.5, nonoil: -7.3 },
  { year: '2021', overall: 20.1, nonoil: 4.6 },
  { year: '2022', overall: 63.3, nonoil: 11.5 },
  { year: '2023', overall: 33.0, nonoil: 11.7 },
  { year: '2024', overall: 43.6, nonoil: 8.5 },
  { year: '2025', overall: 14.4, nonoil: 6.3 },
];

// NPL ratio, quarterly
export const NPL_SERIES: NplRow[] = [
  { q: '2017Q1', npl: 11.8 },
  { q: '2017Q3', npl: 12.4 },
  { q: '2018Q1', npl: 12.9 },
  { q: '2018Q3', npl: 11.6 },
  { q: '2019Q1', npl: 10.2 },
  { q: '2019Q3', npl: 9.1 },
  { q: '2020Q1', npl: 8.4 },
  { q: '2020Q3', npl: 7.6 },
  { q: '2021Q1', npl: 7.0 },
  { q: '2021Q3', npl: 6.2 },
  { q: '2022Q1', npl: 5.8 },
  { q: '2022Q3', npl: 5.3 },
  { q: '2023Q1', npl: 5.0 },
  { q: '2023Q3', npl: 4.7 },
  { q: '2024Q1', npl: 4.4 },
  { q: '2024Q3', npl: 4.2 },
  { q: '2025Q1', npl: 4.3 },
  { q: '2025Q3', npl: 4.5 },
  { q: '2025Q4', npl: 4.6 },
];

export const SAVED_VIEWS: SavedView[] = [
  {
    id: 'sv1',
    name: 'Monthly Cabinet briefing: credit allocation',
    query: 'private sector credit by sector since 2015',
    indicators: ['PSC Business', 'PSC Mortgages', 'PSC Households'],
    last_run: 'Mar 17, 2026',
    chart: 'area',
  },
  {
    id: 'sv2',
    name: 'NRF performance: actual vs budget',
    query: 'NRF inflows actual vs budget 2020 to 2026',
    indicators: ['NRF Actual', 'NRF Budget'],
    last_run: 'Mar 17, 2026',
    chart: 'bar-paired',
  },
  {
    id: 'sv3',
    name: 'Oil-driven growth divergence',
    query: 'real GDP overall vs non-oil since 2017',
    indicators: ['Real GDP', 'Non-oil GDP'],
    last_run: 'Mar 11, 2026',
    chart: 'line',
  },
  {
    id: 'sv4',
    name: 'Financial stability snapshot',
    query: 'NPL ratio quarterly since 2017',
    indicators: ['NPL Ratio'],
    last_run: 'Mar 02, 2026',
    chart: 'line-fall',
  },
  {
    id: 'sv5',
    name: 'External buffer: reserves trajectory',
    query: 'gross international reserves monthly 2019 to present',
    indicators: ['Reserves'],
    last_run: 'Feb 24, 2026',
    chart: 'area',
  },
  {
    id: 'sv6',
    name: 'Inflation and exchange rate pass-through',
    query: 'CPI inflation and G$/US$ rate since 2020',
    indicators: ['CPI YoY', 'FX Rate'],
    last_run: 'Feb 19, 2026',
    chart: 'dual',
  },
];

export const COMPARISON_TABLES: ComparisonTable[] = [
  {
    id: 'cmp-admin',
    name: 'Selected indicators, by administration',
    description:
      "Averages over each administration's tenure. Values are illustrative.",
    groups: [
      { label: 'APNU+AFC', span: 3, sub: ['2015', '2016 to 2020 avg', '2020'] },
      { label: 'PPP/C', span: 3, sub: ['2020', '2021 to 2025 avg', '2025'] },
    ],
    rows: [
      {
        label: 'Real GDP growth, percent',
        unit: 'percent',
        cells: [3.1, 4.2, 43.5, 43.5, 34.9, 14.4],
      },
      {
        label: 'Non-oil GDP growth, percent',
        unit: 'percent',
        cells: [1.9, 2.4, -7.3, -7.3, 8.5, 6.3],
      },
      {
        label: 'CPI inflation, year avg',
        unit: 'percent',
        cells: [-0.9, 1.4, 0.9, 0.9, 4.3, 2.6],
      },
      {
        label: 'NPL ratio, year-end',
        unit: 'percent',
        cells: [6.9, 11.6, 8.4, 8.4, 4.9, 4.6],
      },
      {
        label: 'NRF inflows, US$ millions',
        unit: 'US$m',
        cells: [null, null, 70, 70, 1688, 2450],
      },
      {
        label: 'Gross reserves, US$ millions',
        unit: 'US$m',
        cells: [598, 540, 690, 690, 812, 1010],
      },
    ],
  },
  {
    id: 'cmp-beneficiaries',
    name: 'Social programme beneficiaries, headcount',
    description: 'Enumerated beneficiaries per year.',
    groups: [{ label: 'Year', span: 4, sub: ['2022', '2023', '2024', '2025'] }],
    rows: [
      {
        label: 'BECAUSE cash transfer',
        unit: 'persons',
        cells: [48000, 61200, 74800, 82100],
      },
      {
        label: 'Public assistance',
        unit: 'persons',
        cells: [19800, 20600, 21100, 21800],
      },
      {
        label: 'Old age pension',
        unit: 'persons',
        cells: [64500, 66800, 69200, 71400],
      },
      {
        label: 'School uniform voucher',
        unit: 'persons',
        cells: [205000, 212000, 218000, 224000],
      },
    ],
  },
  {
    id: 'cmp-sectors',
    name: 'Sectoral GDP contribution, share of total',
    description: 'Share of nominal GDP at producer prices.',
    groups: [{ label: 'Year', span: 4, sub: ['2017', '2020', '2022', '2025'] }],
    rows: [
      { label: 'Agriculture', unit: 'percent', cells: [14.8, 9.6, 5.1, 4.2] },
      {
        label: 'Mining and quarrying (ex-oil)',
        unit: 'percent',
        cells: [12.1, 8.4, 4.9, 3.8],
      },
      {
        label: 'Crude oil and gas',
        unit: 'percent',
        cells: [0.0, 34.2, 62.0, 64.5],
      },
      { label: 'Manufacturing', unit: 'percent', cells: [8.2, 5.9, 3.6, 3.1] },
      { label: 'Construction', unit: 'percent', cells: [4.5, 5.1, 4.9, 5.6] },
      { label: 'Services', unit: 'percent', cells: [60.4, 36.8, 19.5, 18.8] },
    ],
  },
];

export const INGESTION_RUN: IngestionRun = {
  timestamp: 'Mar 17, 2026 at 09:14 GYT',
  workbook: 'Guyana Key Statistics v2026.03.xlsx',
  workbook_size: '4.8 MB',
  sheets_parsed: 61,
  indicators_upserted: 1384,
  observations_upserted: 94726,
  duration: '38.2 seconds',
  issues_count: 14,
  quarantine: [
    {
      sheet: 'Fiscal_22',
      cell: 'F47',
      reason: 'Merged cell spans two indicator rows; cannot disambiguate.',
      severity: 'high',
    },
    {
      sheet: 'External_11',
      cell: 'K118',
      reason: 'Non-numeric value "n.a." in a numeric column.',
      severity: 'low',
    },
    {
      sheet: 'External_11',
      cell: 'K119',
      reason: 'Non-numeric value "n.a." in a numeric column.',
      severity: 'low',
    },
    {
      sheet: 'Monetary_11',
      cell: 'D3',
      reason: 'Header row has no unit annotation; defaulted to percent.',
      severity: 'medium',
    },
    {
      sheet: 'Debt_02',
      cell: 'H204',
      reason:
        'Value 0 in a series previously non-zero; flagged for review.',
      severity: 'medium',
    },
    {
      sheet: 'Social_17',
      cell: 'C9',
      reason:
        'Date string "FY24/25" could not be mapped to a single calendar year.',
      severity: 'high',
    },
    {
      sheet: 'Social_31',
      cell: 'E22',
      reason: 'Formula reference #REF! in source; cell skipped.',
      severity: 'high',
    },
    {
      sheet: 'Macro_01',
      cell: 'G2',
      reason:
        'Footnote superscript embedded in value: "43.5¹". Stripped and ingested.',
      severity: 'low',
    },
    {
      sheet: 'Macro_12',
      cell: 'P88',
      reason: 'Row label blank; indicator cannot be named.',
      severity: 'high',
    },
    {
      sheet: 'External_04',
      cell: 'B3',
      reason:
        'Unit cell contains "G$ / US$" with non-standard slash character.',
      severity: 'low',
    },
    {
      sheet: 'Fiscal_01',
      cell: 'AA55',
      reason: 'Column beyond documented schema; ignored.',
      severity: 'medium',
    },
    {
      sheet: 'External_21',
      cell: 'D14',
      reason: 'Negative oil production value in a cumulative series.',
      severity: 'high',
    },
    {
      sheet: 'Debt_03',
      cell: 'F77',
      reason: 'Duplicate quarter label (2023Q2) appears twice in same row.',
      severity: 'medium',
    },
    {
      sheet: 'Monetary_21',
      cell: 'J8',
      reason: 'Rate of 0.00 recorded where previous month was 4.05.',
      severity: 'medium',
    },
  ],
};
